import { getClubBadgeUrl } from "./club-badges";
import type {
  FeedItem,
  LeaderboardEntry,
  League,
  Match,
  Prediction,
} from "./types";

function plMatch(
  id: string,
  home: string,
  homeCode: string,
  away: string,
  awayCode: string,
  kickoff: string,
  matchweekNumber: number,
  venue: string,
  status: Match["status"],
  homeScore?: number,
  awayScore?: number
): Match {
  return {
    id,
    teamA: home,
    teamB: away,
    teamACode: homeCode,
    teamBCode: awayCode,
    homeLogoUrl: getClubBadgeUrl(homeCode, home) ?? undefined,
    awayLogoUrl: getClubBadgeUrl(awayCode, away) ?? undefined,
    kickoffTime: kickoff,
    matchweekNumber,
    venue,
    status,
    homeScore,
    awayScore,
  };
}

/** Official 2026/27 Premier League matchweeks 1–2 (Premier League / BBC Sport). */
export const mockMatches: Match[] = [
  plMatch("pl26-mw1-1", "Arsenal", "ARS", "Coventry City", "COV", "2026-08-21T20:00:00+01:00", 1, "Emirates Stadium", "FT", 3, 0),
  plMatch("pl26-mw1-2", "Hull City", "HUL", "Manchester United", "MUN", "2026-08-22T12:30:00+01:00", 1, "MKM Stadium", "FT", 2, 0),
  plMatch("pl26-mw1-3", "Everton", "EVE", "Crystal Palace", "CRY", "2026-08-22T15:00:00+01:00", 1, "Hill Dickinson Stadium", "FT", 2, 0),
  plMatch("pl26-mw1-4", "Ipswich Town", "IPS", "Sunderland", "SUN", "2026-08-22T15:00:00+01:00", 1, "Portman Road", "FT", 2, 1),
  plMatch("pl26-mw1-5", "Nottingham Forest", "NFO", "Leeds United", "LEE", "2026-08-22T15:00:00+01:00", 1, "City Ground", "FT", 0, 1),
  plMatch("pl26-mw1-6", "Brentford", "BRE", "Tottenham Hotspur", "TOT", "2026-08-22T17:30:00+01:00", 1, "Gtech Community Stadium", "FT", 3, 0),
  plMatch("pl26-mw1-7", "Brighton & Hove Albion", "BHA", "Aston Villa", "AVL", "2026-08-23T14:00:00+01:00", 1, "American Express Stadium", "FT", 4, 0),
  plMatch("pl26-mw1-8", "Manchester City", "MCI", "Bournemouth", "BOU", "2026-08-23T14:00:00+01:00", 1, "Etihad Stadium", "FT", 2, 1),
  plMatch("pl26-mw1-9", "Newcastle United", "NEW", "Liverpool", "LIV", "2026-08-23T16:30:00+01:00", 1, "St James' Park", "FT", 2, 2),
  plMatch("pl26-mw1-10", "Fulham", "FUL", "Chelsea", "CHE", "2026-08-24T20:00:00+01:00", 1, "Craven Cottage", "NS"),
  plMatch("pl26-mw2-1", "Crystal Palace", "CRY", "Manchester City", "MCI", "2026-08-28T20:00:00+01:00", 2, "Selhurst Park", "NS"),
  plMatch("pl26-mw2-2", "Liverpool", "LIV", "Nottingham Forest", "NFO", "2026-08-29T12:30:00+01:00", 2, "Anfield", "NS"),
  plMatch("pl26-mw2-3", "Bournemouth", "BOU", "Everton", "EVE", "2026-08-29T15:00:00+01:00", 2, "Vitality Stadium", "NS"),
  plMatch("pl26-mw2-4", "Coventry City", "COV", "Hull City", "HUL", "2026-08-29T15:00:00+01:00", 2, "Coventry Building Society Arena", "NS"),
  plMatch("pl26-mw2-5", "Tottenham Hotspur", "TOT", "Newcastle United", "NEW", "2026-08-29T17:30:00+01:00", 2, "Tottenham Hotspur Stadium", "NS"),
  plMatch("pl26-mw2-6", "Chelsea", "CHE", "Brighton & Hove Albion", "BHA", "2026-08-30T14:00:00+01:00", 2, "Stamford Bridge", "NS"),
  plMatch("pl26-mw2-7", "Leeds United", "LEE", "Brentford", "BRE", "2026-08-30T14:00:00+01:00", 2, "Elland Road", "NS"),
  plMatch("pl26-mw2-8", "Sunderland", "SUN", "Fulham", "FUL", "2026-08-30T14:00:00+01:00", 2, "Stadium of Light", "NS"),
  plMatch("pl26-mw2-9", "Manchester United", "MUN", "Ipswich Town", "IPS", "2026-08-30T16:30:00+01:00", 2, "Old Trafford", "NS"),
  plMatch("pl26-mw2-10", "Aston Villa", "AVL", "Arsenal", "ARS", "2026-08-31T20:00:00+01:00", 2, "Villa Park", "NS"),
];

export const mockFeedItems: FeedItem[] = [
  {
    id: "f1",
    type: "banter",
    title: "Bold call!",
    body: "You predicted Morocco to beat Spain. 92% of users disagreed. You were right.",
    media: {
      type: "gif",
      url: "/reactions/receipts-found.svg",
      alt: "Celebration reaction",
    },
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    likes: 142,
  },
  {
    id: "f2",
    type: "meme",
    title: "Hall of Shame",
    body: "Your friend's 3-0 prediction aged like milk. Final score: 0-1.",
    media: {
      type: "gif",
      url: "/reactions/brave-but-wrong.svg",
      alt: "Reaction GIF - prediction failed",
    },
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    likes: 89,
  },
  {
    id: "f3",
    type: "news",
    title: "Premier League Preview",
    body: "Analysts expect a tight title race as the big six open the new Premier League campaign.",
    source: "ESPN",
    sourceUrl: "https://espn.com",
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "f4",
    type: "leaderboard",
    title: "Weekly Winner",
    body: "Alex topped your league with 24 points this matchday. Can you catch up?",
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    likes: 56,
  },
  {
    id: "f5",
    type: "prediction_highlight",
    title: "Perfect Score",
    body: "Jamie nailed a 2-1 correct score for +7 points. That's how it's done.",
    publishedAt: new Date(Date.now() - 18000000).toISOString(),
    likes: 203,
  },
  {
    id: "f6",
    type: "banter",
    title: "Pundit Roast",
    body: "Your prediction accuracy is currently being investigated by scientists.",
    media: {
      type: "gif",
      url: "/reactions/prediction-fraud.svg",
      alt: "Skeptical reaction",
    },
    publishedAt: new Date(Date.now() - 21600000).toISOString(),
    likes: 312,
  },
  {
    id: "f7",
    type: "meme",
    title: "I know ball… watch me!",
    body: "When your pre-match script hits different and the goal goes in off the crossbar.",
    media: {
      type: "clip",
      url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      posterUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=640&h=360&fit=crop",
      audioUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3",
      alt: "Goal celebration clip with sound bite",
    },
    publishedAt: new Date(Date.now() - 25200000).toISOString(),
    likes: 428,
  },
  {
    id: "f8",
    type: "prediction_highlight",
    title: "Called it on camera",
    body: "Exported his TikTok script before kickoff — 2-1 final. Content creator mode activated.",
    media: {
      type: "video",
      url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/friday.mp4",
      alt: "Short highlight clip",
    },
    publishedAt: new Date(Date.now() - 28800000).toISOString(),
    likes: 567,
  },
];

export const mockGlobalLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "u1",
    displayName: "PredictionKing",
    points: 847,
    correctPredictions: 42,
    totalPredictions: 58,
  },
  {
    rank: 2,
    userId: "u2",
    displayName: "GoalOracle",
    points: 812,
    correctPredictions: 39,
    totalPredictions: 55,
  },
  {
    rank: 3,
    userId: "u3",
    displayName: "MatchDayMaven",
    points: 798,
    correctPredictions: 38,
    totalPredictions: 54,
  },
  {
    rank: 4,
    userId: "u4",
    displayName: "You",
    points: 654,
    correctPredictions: 31,
    totalPredictions: 48,
  },
  {
    rank: 5,
    userId: "u5",
    displayName: "FootyFanatic",
    points: 621,
    correctPredictions: 29,
    totalPredictions: 47,
  },
];

export const mockLeagueLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "u2",
    displayName: "Alex",
    points: 156,
    correctPredictions: 12,
    totalPredictions: 16,
  },
  {
    rank: 2,
    userId: "u4",
    displayName: "You",
    points: 142,
    correctPredictions: 11,
    totalPredictions: 16,
  },
  {
    rank: 3,
    userId: "u6",
    displayName: "Sam",
    points: 128,
    correctPredictions: 10,
    totalPredictions: 16,
  },
];

export const mockPunditLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "p1",
    displayName: "Side-View Gary",
    organization: "Rant & Chips TV",
    archetype: "Touchline rage merchant",
    parodyCue: "Parody · the touchline close-up guy (Neville energy)",
    styleSlug: "touchline-uk",
    isFictionalPersona: true,
    points: 412,
    isPundit: true,
    correctPredictions: 28,
    totalPredictions: 40,
  },
  {
    rank: 2,
    userId: "p2",
    displayName: "Sofa Captain Rio",
    organization: "Sofa Champions",
    archetype: "Ex-pro captain couch takes",
    parodyCue: "Parody · the velvet sofa legend (Rio energy)",
    styleSlug: "ex-pro-couch",
    isFictionalPersona: true,
    points: 398,
    isPundit: true,
    correctPredictions: 26,
    totalPredictions: 40,
  },
  {
    rank: 3,
    userId: "p3",
    displayName: "Screamin' Stephen",
    organization: "First Controversy Desk",
    archetype: "Loudest desk in the building",
    parodyCue: "Parody · controversy merchant (Stephen A. energy)",
    styleSlug: "hot-take-desk",
    isFictionalPersona: true,
    points: 385,
    isPundit: true,
    correctPredictions: 25,
    totalPredictions: 40,
  },
  {
    rank: 4,
    userId: "p4",
    displayName: "Le Prof Henri",
    organization: "Class on Grass",
    archetype: "Silky studio icon",
    parodyCue: "Parody · the smooth studio legend (Henry energy)",
    styleSlug: "silky-studio",
    isFictionalPersona: true,
    points: 372,
    isPundit: true,
    correctPredictions: 24,
    totalPredictions: 40,
  },
];

export const mockFriendsLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "u7",
    displayName: "Chris",
    points: 178,
    correctPredictions: 13,
    totalPredictions: 16,
  },
  {
    rank: 2,
    userId: "u4",
    displayName: "You",
    points: 142,
    correctPredictions: 11,
    totalPredictions: 16,
  },
  {
    rank: 3,
    userId: "u8",
    displayName: "Taylor",
    points: 119,
    correctPredictions: 9,
    totalPredictions: 16,
  },
];

export const mockSystemLeagues: League[] = [
  {
    id: "global-1",
    name: "Global Banter League",
    inviteCode: "GLOBAL",
    memberCount: 1842,
    kind: "global",
    points: 86,
  },
  {
    id: "country-gb",
    name: "United Kingdom Fans",
    inviteCode: "CTRYGB",
    memberCount: 312,
    kind: "country",
    countryCode: "GB",
    points: 86,
  },
];

export const mockLeagues: League[] = [
  ...mockSystemLeagues,
  {
    id: "l1",
    name: "Office Premier League Pool",
    inviteCode: "PL2026-ABC",
    memberCount: 12,
    kind: "custom",
    isAdmin: true,
    myDisplayName: "You",
    rank: 2,
    points: 142,
  },
  {
    id: "l2",
    name: "Family Predictions",
    kind: "custom",
    inviteCode: "FAM-2026",
    memberCount: 6,
    ownerName: "Mom",
    rank: 1,
    points: 156,
  },
];

export const mockPredictionHistory: Prediction[] = [
  {
    id: "pred1",
    matchId: "past1",
    predictionType: "result",
    predictionValue: "home",
    pointsAwarded: 3,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    match: {
      id: "past1",
      teamA: "Japan",
      teamB: "Colombia",
      kickoffTime: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
  },
  {
    id: "pred2",
    matchId: "past2",
    predictionType: "correct_score",
    predictionValue: "2-1",
    pointsAwarded: 7,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    match: {
      id: "past2",
      teamA: "Netherlands",
      teamB: "Mexico",
      kickoffTime: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
  },
  {
    id: "pred3",
    matchId: "past3",
    predictionType: "double_chance",
    predictionValue: "home_or_draw",
    pointsAwarded: 0,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    match: {
      id: "past3",
      teamA: "Portugal",
      teamB: "Uruguay",
      kickoffTime: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
  },
];
