export const SCORING_RULES = [
  {
    title: "Match result (Home / Draw / Away)",
    points: 3,
    description: "Pick the correct outcome of the full match.",
    example: "You pick Arsenal to win — Arsenal wins 2-1 → +3 points.",
  },
  {
    title: "Correct score",
    points: 7,
    description: "Call the exact final scoreline.",
    example: "You pick 2-1 — final is 2-1 → +7 points.",
  },
  {
    title: "Double chance",
    points: 2,
    description: "Cover two of the three possible outcomes in one pick.",
    example: "Home or Draw — if Arsenal win or draw → +2 points.",
  },
  {
    title: "Perfect matchweek",
    points: 5,
    bonus: true,
    description: "Bonus when every result pick in a matchweek is correct.",
    example: "All your result picks hit in Matchweek 12 → +5 bonus.",
  },
] as const;

export const TOURNAMENT_BONUS_RULES = [
  {
    id: "league_winner",
    title: "League winner",
    points: 50,
    difficulty: "Expert",
    description: "Who lifts the Premier League trophy?",
    example: "You pick Arsenal — they win the league → +50 points.",
    isTeamPick: true,
  },
  {
    id: "player_of_the_season",
    title: "Player of the Season",
    points: 50,
    difficulty: "Expert",
    description: "Call the official Player of the Season.",
    example: "You pick Palmer — he wins POTS → +50 points.",
    isTeamPick: false,
  },
  {
    id: "golden_boot",
    title: "Golden Boot",
    points: 40,
    difficulty: "Hard",
    description: "Who finishes as the Premier League's leading goal scorer?",
    example: "You pick Haaland — he wins the Golden Boot → +40 points.",
    isTeamPick: false,
  },
  {
    id: "most_assists",
    title: "Most assists",
    points: 35,
    difficulty: "Hard",
    description: "Who leads the Premier League in assists?",
    example: "You pick Saka — he tops assists → +35 points.",
    isTeamPick: false,
  },
  {
    id: "golden_glove",
    title: "Golden Glove",
    points: 35,
    difficulty: "Hard",
    description: "Which goalkeeper wins the Golden Glove?",
    example: "You pick Raya — Golden Glove winner → +35 points.",
    isTeamPick: false,
  },
  {
    id: "young_player_of_the_season",
    title: "Young Player of the Season",
    points: 35,
    difficulty: "Hard",
    description: "Who wins Young Player of the Season?",
    example: "You pick Lewis-Skelly — he wins YPOTS → +35 points.",
    isTeamPick: false,
  },
  {
    id: "top_four",
    title: "Top four",
    points: 20,
    difficulty: "Hard",
    description: "Name the four clubs that finish in Champions League places. +20 per correct club.",
    example: "You pick Arsenal, City, Liverpool, Chelsea — three finish top four → +60.",
    isTeamPick: true,
  },
  {
    id: "relegated",
    title: "Relegated",
    points: 20,
    difficulty: "Hard",
    description: "Name the three clubs that go down. +20 per correct club.",
    example: "You call two of the three correctly → +40.",
    isTeamPick: true,
  },
  {
    id: "surprise_team",
    title: "Surprise team",
    points: 30,
    difficulty: "Tricky",
    description: "Which club exceeds expectations this season?",
    example: "You pick Forest — they smash their expected finish → +30 points.",
    isTeamPick: true,
  },
] as const;

export const TOURNAMENT_BONUS_ELIGIBILITY = {
  minCustomLeagueMembers: 3,
  summary:
    "Anyone with an active session can save season awards before the first kickoff. Award points only count on private league leaderboards with at least 3 members, after you've made at least one match pick. Global and Country leagues never include award points.",
} as const;

export const CONCEPT_SLIDES = [
  {
    id: "picks",
    title: "Lock picks before kickoff",
    subtitle: "Step 1 · Predict",
    body: "Tap a matchweek fixture, choose result, exact score, or double chance — save it to your session in seconds. No account needed to start; your browser keeps your slate.",
    accent: "pitch",
    backgroundImage: "/images/baller-score-points.png",
    highlights: ["Result · score · double", "Saved to your session", "Kickoff deadlines"],
    stickerImage: "/reactions/locked-in.svg",
  },
  {
    id: "banter",
    title: "Scroll banter that hits different",
    subtitle: "Step 2 · Watch",
    body: "Your feed mixes your picks vs reality, pundit hot takes, RSS + YouTube clips, and AI reactions with GIFs and memes — built for matchday group-chat energy.",
    accent: "brand",
    backgroundImage: "/images/banter-feed-hero.png",
    highlights: ["GIF reactions", "Pundit source tags", "Picks vs reality"],
    stickerImage: "/reactions/receipts-found.svg",
  },
  {
    id: "content",
    title: "Turn picks into post-ready scripts",
    subtitle: "Step 3 · Create",
    body: "Studio exports one cumulative script for every pick — pre-match bold calls or post-match flex and roast — formatted for TikTok, Reels, and Shorts with stats baked in.",
    accent: "gold",
    backgroundImage: "/images/baller-scripts.png",
    highlights: ["Pre + post scripts", "Copy & film", "All picks in one export"],
    stickerImage: "/reactions/script-writer.svg",
  },
  {
    id: "scoring",
    title: "Points that actually mean something",
    subtitle: "How you eat",
    body: "Result +3 · exact score +7 · double chance +2. Nail a perfect matchweek for +5. Private leagues unlock season awards for extra swings.",
    accent: "pitch",
    backgroundImage: "/images/score-points-your-way.png",
    highlights: ["+7 exact score", "Perfect week bonus", "Big league swings"],
    stickerImage: "/reactions/smart-choice.svg",
  },
  {
    id: "bonuses",
    title: "Season awards for the bold",
    subtitle: "High risk · high flex",
    body: "League winner, Golden Boot, relegation, Player of the Season — lock them before the campaign runs away. Only scores in custom leagues with 3+ people actually playing.",
    accent: "flare",
    backgroundImage: "/images/bonus-picks.png",
    highlights: ["+50 title call", "Private leagues only", "Flex when it lands"],
    stickerImage: "/reactions/chaos-pick.svg",
  },
  {
    id: "leagues",
    title: "Leagues = weekly drama",
    subtitle: "Your squad",
    body: "Spin up a private league, drop the invite in the group chat, and let matchweek + season standings turn every Saturday into an argument worth having.",
    accent: "brand",
    backgroundImage: "/images/ball-knowledge-header.png",
    highlights: ["Invite code", "Matchweek standings", "Global + country boards"],
  },
  {
    id: "pundits",
    title: "Beat the board, then the group chat",
    subtitle: "Aura rankings",
    body: "Your picks stack on the same leaderboard as mates. Outrank them and you've got clip material for days.",
    accent: "gold",
    backgroundImage: "/images/ball-knowledge-header.png",
    highlights: ["Private leagues", "Aura rankings", "Receipts when you're right"],
    stickerImage: "/reactions/against-grain.svg",
  },
] as const;

export const HOME_WELCOME_SLIDES = [
  {
    id: "welcome",
    title: "Think you know ball? Prove it.",
    subtitle: "Premier League · free to play",
    body: "Predict the Premier League. Beat your mates. Come back next matchweek.",
    accent: "brand",
    backgroundImage: "/images/welcome-hero-panel.png",
    highlights: ["No account needed", "38 matchweeks"],
    stickerImage: "/reactions/locked-in.svg",
  },
  ...CONCEPT_SLIDES,
] as const;
