// <auto-generated />
using System;
using BanterApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BanterApp.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613000313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanterApp.Api.Data.Entities.AnonymousUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiGenerationsUsed")
                        .HasColumnType("integer");

                    b.Property<string>("CookieId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RecoveryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CookieId")
                        .IsUnique();

                    b.ToTable("anonymous_users", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.BracketPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonymousUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WinnerTeamCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("AnonymousUserId", "SlotId");

                    b.HasIndex("UserId", "SlotId");

                    b.ToTable("bracket_picks", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.GeneratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonymousUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousUserId");

                    b.HasIndex("UserId");

                    b.ToTable("generated_content", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAnonymousUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAnonymousUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("Kind", "CountryCode");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonymousUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "AnonymousUserId");

                    b.HasIndex("LeagueId", "UserId");

                    b.ToTable("league_members", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("KickoffTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamACode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamBCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.NewsFeedItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ParentItemId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("news_feed_items", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonymousUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<int>("PredictionType")
                        .HasColumnType("integer");

                    b.Property<string>("PredictionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("AnonymousUserId", "MatchId", "PredictionType");

                    b.HasIndex("UserId", "MatchId", "PredictionType");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.Pundit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pundits", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.PunditPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PunditId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PunditId");

                    b.ToTable("pundit_predictions", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAdultVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.BracketPick", b =>
                {
                    b.HasOne("BanterApp.Api.Data.Entities.AnonymousUser", "AnonymousUser")
                        .WithMany("BracketPicks")
                        .HasForeignKey("AnonymousUserId");

                    b.HasOne("BanterApp.Api.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterApp.Api.Data.Entities.User", "User")
                        .WithMany("BracketPicks")
                        .HasForeignKey("UserId");

                    b.Navigation("AnonymousUser");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.GeneratedContent", b =>
                {
                    b.HasOne("BanterApp.Api.Data.Entities.AnonymousUser", "AnonymousUser")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("AnonymousUserId");

                    b.HasOne("BanterApp.Api.Data.Entities.User", "User")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("UserId");

                    b.Navigation("AnonymousUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.League", b =>
                {
                    b.HasOne("BanterApp.Api.Data.Entities.AnonymousUser", "CreatedByAnonymousUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAnonymousUserId");

                    b.HasOne("BanterApp.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByAnonymousUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.LeagueMember", b =>
                {
                    b.HasOne("BanterApp.Api.Data.Entities.AnonymousUser", "AnonymousUser")
                        .WithMany()
                        .HasForeignKey("AnonymousUserId");

                    b.HasOne("BanterApp.Api.Data.Entities.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterApp.Api.Data.Entities.User", "User")
                        .WithMany("LeagueMemberships")
                        .HasForeignKey("UserId");

                    b.Navigation("AnonymousUser");

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.Prediction", b =>
                {
                    b.HasOne("BanterApp.Api.Data.Entities.AnonymousUser", "AnonymousUser")
                        .WithMany("Predictions")
                        .HasForeignKey("AnonymousUserId");

                    b.HasOne("BanterApp.Api.Data.Entities.Match", "Match")
                        .WithMany("Predictions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterApp.Api.Data.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId");

                    b.Navigation("AnonymousUser");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.PunditPrediction", b =>
                {
                    b.HasOne("BanterApp.Api.Data.Entities.Match", "Match")
                        .WithMany("PunditPredictions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanterApp.Api.Data.Entities.Pundit", "Pundit")
                        .WithMany("Predictions")
                        .HasForeignKey("PunditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Pundit");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.AnonymousUser", b =>
                {
                    b.Navigation("BracketPicks");

                    b.Navigation("GeneratedContents");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.League", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.Match", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("PunditPredictions");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.Pundit", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("BanterApp.Api.Data.Entities.User", b =>
                {
                    b.Navigation("BracketPicks");

                    b.Navigation("GeneratedContents");

                    b.Navigation("LeagueMemberships");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
